//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXONSYSTEM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXONSYSTEM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTAQuizNN.
        /// </summary>
        public static string DATABASE_NAME {
            get {
                return ResourceManager.GetString("DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234@abcd.
        /// </summary>
        public static string DATABASE_PASS {
            get {
                return ResourceManager.GetString("DATABASE_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1433.
        /// </summary>
        public static string DATABASE_PORT {
            get {
                return ResourceManager.GetString("DATABASE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        public static string DATABASE_USER {
            get {
                return ResourceManager.GetString("DATABASE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMG_ERROR {
            get {
                object obj = ResourceManager.GetObject("IMG_ERROR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMG_INFORMATION {
            get {
                object obj = ResourceManager.GetObject("IMG_INFORMATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMG_NOTIFICATION {
            get {
                object obj = ResourceManager.GetObject("IMG_NOTIFICATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMG_SUCCESS {
            get {
                object obj = ResourceManager.GetObject("IMG_SUCCESS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123123.
        /// </summary>
        public static string IP_DB {
            get {
                return ResourceManager.GetString("IP_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 172.20.10.7.
        /// </summary>
        public static string IP_SUPERVISOR {
            get {
                return ResourceManager.GetString("IP_SUPERVISOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MEDIA {
            get {
                object obj = ResourceManager.GetObject("MEDIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MEDIAPLAY {
            get {
                object obj = ResourceManager.GetObject("MEDIAPLAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối.
        /// </summary>
        public static string MSG_CON_0001 {
            get {
                return ResourceManager.GetString("MSG_CON_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối tới máy chủ!.
        /// </summary>
        public static string MSG_CON_0002 {
            get {
                return ResourceManager.GetString("MSG_CON_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string MSG_GUI_0001 {
            get {
                return ResourceManager.GetString("MSG_GUI_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string MSG_GUI_0002 {
            get {
                return ResourceManager.GetString("MSG_GUI_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND.
        /// </summary>
        public static string MSG_GUI_0003 {
            get {
                return ResourceManager.GetString("MSG_GUI_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➤ Thông tin thí sinh.
        /// </summary>
        public static string MSG_GUI_0004 {
            get {
                return ResourceManager.GetString("MSG_GUI_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➤ Thông tin kỳ thi.
        /// </summary>
        public static string MSG_GUI_0005 {
            get {
                return ResourceManager.GetString("MSG_GUI_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kỳ thi.
        /// </summary>
        public static string MSG_GUI_0006 {
            get {
                return ResourceManager.GetString("MSG_GUI_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thi.
        /// </summary>
        public static string MSG_GUI_0007 {
            get {
                return ResourceManager.GetString("MSG_GUI_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn thi.
        /// </summary>
        public static string MSG_GUI_0008 {
            get {
                return ResourceManager.GetString("MSG_GUI_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Báo lỗi.
        /// </summary>
        public static string MSG_GUI_0009 {
            get {
                return ResourceManager.GetString("MSG_GUI_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sẵn sàng.
        /// </summary>
        public static string MSG_GUI_0010 {
            get {
                return ResourceManager.GetString("MSG_GUI_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nộp bài.
        /// </summary>
        public static string MSG_GUI_0011 {
            get {
                return ResourceManager.GetString("MSG_GUI_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string MSG_GUI_0012 {
            get {
                return ResourceManager.GetString("MSG_GUI_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám thị.
        /// </summary>
        public static string MSG_GUI_0013 {
            get {
                return ResourceManager.GetString("MSG_GUI_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm bài.
        /// </summary>
        public static string MSG_GUI_0014 {
            get {
                return ResourceManager.GetString("MSG_GUI_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XÁC NHẬN.
        /// </summary>
        public static string MSG_GUI_0015 {
            get {
                return ResourceManager.GetString("MSG_GUI_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP ➜.
        /// </summary>
        public static string MSG_GUI_0016 {
            get {
                return ResourceManager.GetString("MSG_GUI_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBD.
        /// </summary>
        public static string MSG_GUI_0017 {
            get {
                return ResourceManager.GetString("MSG_GUI_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0}.
        /// </summary>
        public static string MSG_GUI_0018 {
            get {
                return ResourceManager.GetString("MSG_GUI_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to »HỆ THỐNG THI TRỰC TUYẾN«.
        /// </summary>
        public static string MSG_GUI_0019 {
            get {
                return ResourceManager.GetString("MSG_GUI_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu {0}..
        /// </summary>
        public static string MSG_GUI_0020 {
            get {
                return ResourceManager.GetString("MSG_GUI_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string MSG_GUI_0021 {
            get {
                return ResourceManager.GetString("MSG_GUI_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A..
        /// </summary>
        public static string MSG_GUI_0022 {
            get {
                return ResourceManager.GetString("MSG_GUI_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B..
        /// </summary>
        public static string MSG_GUI_0023 {
            get {
                return ResourceManager.GetString("MSG_GUI_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C..
        /// </summary>
        public static string MSG_GUI_0024 {
            get {
                return ResourceManager.GetString("MSG_GUI_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D..
        /// </summary>
        public static string MSG_GUI_0025 {
            get {
                return ResourceManager.GetString("MSG_GUI_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;font-weight: bold&quot;&gt;&lt;u&gt;Câu {0}:&lt;/u&gt;&lt;/span&gt; {1}.
        /// </summary>
        public static string MSG_GUI_0026 {
            get {
                return ResourceManager.GetString("MSG_GUI_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải đề thi.
        /// </summary>
        public static string MSG_GUI_0027 {
            get {
                return ResourceManager.GetString("MSG_GUI_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải...{0}%.
        /// </summary>
        public static string MSG_GUI_0028 {
            get {
                return ResourceManager.GetString("MSG_GUI_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Xong.
        /// </summary>
        public static string MSG_GUI_0029 {
            get {
                return ResourceManager.GetString("MSG_GUI_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string MSG_GUI_0030 {
            get {
                return ResourceManager.GetString("MSG_GUI_0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string MSG_GUI_0031 {
            get {
                return ResourceManager.GetString("MSG_GUI_0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string MSG_GUI_0032 {
            get {
                return ResourceManager.GetString("MSG_GUI_0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MSG_GUI_0033 {
            get {
                return ResourceManager.GetString("MSG_GUI_0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuẩn bị sẵn sàng làm bài thi. Chúc bạn làm bài thật tốt!.
        /// </summary>
        public static string MSG_GUI_0034 {
            get {
                return ResourceManager.GetString("MSG_GUI_0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã nhập sai 3 lần..
        /// </summary>
        public static string MSG_GUI_0035 {
            get {
                return ResourceManager.GetString("MSG_GUI_0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng thi.
        /// </summary>
        public static string MSG_GUI_0036 {
            get {
                return ResourceManager.GetString("MSG_GUI_0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy thi.
        /// </summary>
        public static string MSG_GUI_0037 {
            get {
                return ResourceManager.GetString("MSG_GUI_0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập với &quot;{0}&quot;.
        /// </summary>
        public static string MSG_GUI_0038 {
            get {
                return ResourceManager.GetString("MSG_GUI_0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số báo danh.
        /// </summary>
        public static string MSG_GUI_0041 {
            get {
                return ResourceManager.GetString("MSG_GUI_0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sinh viên.
        /// </summary>
        public static string MSG_GUI_0042 {
            get {
                return ResourceManager.GetString("MSG_GUI_0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND.
        /// </summary>
        public static string MSG_GUI_0043 {
            get {
                return ResourceManager.GetString("MSG_GUI_0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bạn nhập vào không tồn tại hoặc bạn đã đăng nhập sai phòng thi.
        /// </summary>
        public static string MSG_GUI_0044 {
            get {
                return ResourceManager.GetString("MSG_GUI_0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string MSG_GUI_0045 {
            get {
                return ResourceManager.GetString("MSG_GUI_0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string MSG_GUI_0046 {
            get {
                return ResourceManager.GetString("MSG_GUI_0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn máy thi của bạn gặp sự cố và cần sự giúp đỡ của giám thị viên?.
        /// </summary>
        public static string MSG_GUI_0047 {
            get {
                return ResourceManager.GetString("MSG_GUI_0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Phút.
        /// </summary>
        public static string MSG_GUI_0048 {
            get {
                return ResourceManager.GetString("MSG_GUI_0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca thi.
        /// </summary>
        public static string MSG_GUI_0049 {
            get {
                return ResourceManager.GetString("MSG_GUI_0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả thi.
        /// </summary>
        public static string MSG_GUI_0050 {
            get {
                return ResourceManager.GetString("MSG_GUI_0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điểm thi trắc nghiệm bạn đạt được là: {0} điểm trên tổng số {1} điểm.
        /// </summary>
        public static string MSG_GUI_0051 {
            get {
                return ResourceManager.GetString("MSG_GUI_0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng nhập sai máy thi..
        /// </summary>
        public static string MSG_GUI_0052 {
            get {
                return ResourceManager.GetString("MSG_GUI_0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã vi phạm lần {0} trừ {1}% tổng số điểm..
        /// </summary>
        public static string MSG_GUI_0053 {
            get {
                return ResourceManager.GetString("MSG_GUI_0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã vi phạm quy chế thi lần thứ {0} và bị trừ {1}% tổng số điểm. Nếu vi phạm 3 lần, bài thi của bạn sẽ bị hủy..
        /// </summary>
        public static string MSG_GUI_0054 {
            get {
                return ResourceManager.GetString("MSG_GUI_0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã vi phạm quy chế thi 3 lần. Bài thi của bạn bị hủy..
        /// </summary>
        public static string MSG_GUI_0055 {
            get {
                return ResourceManager.GetString("MSG_GUI_0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn thi: {0}..
        /// </summary>
        public static string MSG_GUI_0056 {
            get {
                return ResourceManager.GetString("MSG_GUI_0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thi: {0} | Ca thi: {1} - {2}..
        /// </summary>
        public static string MSG_GUI_0057 {
            get {
                return ResourceManager.GetString("MSG_GUI_0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công. Vui lòng chờ để nhận đề bài..
        /// </summary>
        public static string MSG_GUI_0058 {
            get {
                return ResourceManager.GetString("MSG_GUI_0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuẩn bị sang ca thi tiếp theo. Bạn hãy vui lòng chờ!.
        /// </summary>
        public static string MSG_GUI_0059 {
            get {
                return ResourceManager.GetString("MSG_GUI_0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối với máy giám thị..
        /// </summary>
        public static string MSG_GUI_0060 {
            get {
                return ResourceManager.GetString("MSG_GUI_0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến máy chủ thi..
        /// </summary>
        public static string MSG_GUI_0061 {
            get {
                return ResourceManager.GetString("MSG_GUI_0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai định dạng địa chỉ IP.
        /// </summary>
        public static string MSG_GUI_0062 {
            get {
                return ResourceManager.GetString("MSG_GUI_0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng bạn đã hoàn thành xong bài thi đánh giá năng lực!.
        /// </summary>
        public static string MSG_GUI_0063 {
            get {
                return ResourceManager.GetString("MSG_GUI_0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng bạn đã hoàn thành xong bài thi!.
        /// </summary>
        public static string MSG_GUI_0064 {
            get {
                return ResourceManager.GetString("MSG_GUI_0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời gian bù.
        /// </summary>
        public static string MSG_GUI_0065 {
            get {
                return ResourceManager.GetString("MSG_GUI_0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem lại thời gian gián đoạn.
        /// </summary>
        public static string MSG_GUI_0066 {
            get {
                return ResourceManager.GetString("MSG_GUI_0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu {0} ({1} điểm)..
        /// </summary>
        public static string MSG_GUI_0067 {
            get {
                return ResourceManager.GetString("MSG_GUI_0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp.
        /// </summary>
        public static string MSG_GUI_0068 {
            get {
                return ResourceManager.GetString("MSG_GUI_0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem điểm.
        /// </summary>
        public static string MSG_GUI_0069 {
            get {
                return ResourceManager.GetString("MSG_GUI_0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string MSG_GUI_0070 {
            get {
                return ResourceManager.GetString("MSG_GUI_0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string MSG_LOG_ERROR {
            get {
                return ResourceManager.GetString("MSG_LOG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL.
        /// </summary>
        public static string MSG_LOG_FATAL {
            get {
                return ResourceManager.GetString("MSG_LOG_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string MSG_LOG_INFO {
            get {
                return ResourceManager.GetString("MSG_LOG_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN.
        /// </summary>
        public static string MSG_LOG_WARN {
            get {
                return ResourceManager.GetString("MSG_LOG_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo!.
        /// </summary>
        public static string MSG_MESS_0001 {
            get {
                return ResourceManager.GetString("MSG_MESS_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập {0}.
        /// </summary>
        public static string MSG_MESS_0002 {
            get {
                return ResourceManager.GetString("MSG_MESS_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu..
        /// </summary>
        public static string MSG_MESS_0003 {
            get {
                return ResourceManager.GetString("MSG_MESS_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại.
        /// </summary>
        public static string MSG_MESS_0004 {
            get {
                return ResourceManager.GetString("MSG_MESS_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công!.
        /// </summary>
        public static string MSG_MESS_0005 {
            get {
                return ResourceManager.GetString("MSG_MESS_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng {0} đăng nhập thành công.
        /// </summary>
        public static string MSG_MESS_0006 {
            get {
                return ResourceManager.GetString("MSG_MESS_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESSFULLY!.
        /// </summary>
        public static string MSG_MESS_0007 {
            get {
                return ResourceManager.GetString("MSG_MESS_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START FUNCTION.
        /// </summary>
        public static string MSG_MESS_0008 {
            get {
                return ResourceManager.GetString("MSG_MESS_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END OF FUNCTION.
        /// </summary>
        public static string MSG_MESS_0009 {
            get {
                return ResourceManager.GetString("MSG_MESS_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMCLOSE.
        /// </summary>
        public static string MSG_MESS_0010 {
            get {
                return ResourceManager.GetString("MSG_MESS_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSED.
        /// </summary>
        public static string MSG_MESS_0011 {
            get {
                return ResourceManager.GetString("MSG_MESS_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải đề thi....
        /// </summary>
        public static string MSG_MESS_0012 {
            get {
                return ResourceManager.GetString("MSG_MESS_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin lên server thành công!.
        /// </summary>
        public static string MSG_MESS_0013 {
            get {
                return ResourceManager.GetString("MSG_MESS_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không xác định.
        /// </summary>
        public static string MSG_MESS_0014 {
            get {
                return ResourceManager.GetString("MSG_MESS_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin lên server không thành công.
        /// </summary>
        public static string MSG_MESS_0015 {
            get {
                return ResourceManager.GetString("MSG_MESS_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến máy chủ.
        /// </summary>
        public static string MSG_MESS_0016 {
            get {
                return ResourceManager.GetString("MSG_MESS_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối máy chủ thành công.
        /// </summary>
        public static string MSG_MESS_0017 {
            get {
                return ResourceManager.GetString("MSG_MESS_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa dữ liệu thành công.
        /// </summary>
        public static string MSG_MESS_0018 {
            get {
                return ResourceManager.GetString("MSG_MESS_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa dữ liệu lỗi.
        /// </summary>
        public static string MSG_MESS_0019 {
            get {
                return ResourceManager.GetString("MSG_MESS_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải mã dữ liệu thành công.
        /// </summary>
        public static string MSG_MESS_0020 {
            get {
                return ResourceManager.GetString("MSG_MESS_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải mã dữ liệu lỗi.
        /// </summary>
        public static string MSG_MESS_0021 {
            get {
                return ResourceManager.GetString("MSG_MESS_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách control rỗng..
        /// </summary>
        public static string MSG_MESS_0022 {
            get {
                return ResourceManager.GetString("MSG_MESS_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREAD_GENERATE_{0}_END.
        /// </summary>
        public static string MSG_MESS_0023 {
            get {
                return ResourceManager.GetString("MSG_MESS_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START_THREAD_{0}.
        /// </summary>
        public static string MSG_MESS_0024 {
            get {
                return ResourceManager.GetString("MSG_MESS_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có {0} phút để kiểm tra máy....
        /// </summary>
        public static string MSG_MESS_0025 {
            get {
                return ResourceManager.GetString("MSG_MESS_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        public static string MSG_MESS_0026 {
            get {
                return ResourceManager.GetString("MSG_MESS_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh cáo thí sinh {0} lần thứ {1}.
        /// </summary>
        public static string MSG_MESS_0027 {
            get {
                return ResourceManager.GetString("MSG_MESS_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME OUT.
        /// </summary>
        public static string MSG_MESS_0028 {
            get {
                return ResourceManager.GetString("MSG_MESS_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➤ Chú ý.
        /// </summary>
        public static string MSG_MESS_0029 {
            get {
                return ResourceManager.GetString("MSG_MESS_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Cảnh cáo lần {0} trừ {1}% tổng số điểm..
        /// </summary>
        public static string MSG_MESS_0030 {
            get {
                return ResourceManager.GetString("MSG_MESS_0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Cảnh cáo lần 3 sẽ hủy bài thi..
        /// </summary>
        public static string MSG_MESS_0031 {
            get {
                return ResourceManager.GetString("MSG_MESS_0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm bài bắt đầu! Chúc các bạn thi tốt..
        /// </summary>
        public static string MSG_MESS_0032 {
            get {
                return ResourceManager.GetString("MSG_MESS_0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thi xong.
        /// </summary>
        public static string MSG_MESS_0033 {
            get {
                return ResourceManager.GetString("MSG_MESS_0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thi mới.
        /// </summary>
        public static string MSG_MESS_0034 {
            get {
                return ResourceManager.GetString("MSG_MESS_0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thi nhưng bị gián đoạn.
        /// </summary>
        public static string MSG_MESS_0035 {
            get {
                return ResourceManager.GetString("MSG_MESS_0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đang được sử dụng.
        /// </summary>
        public static string MSG_MESS_0036 {
            get {
                return ResourceManager.GetString("MSG_MESS_0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập sai lần thứ {0}.
        /// </summary>
        public static string MSG_MESS_0037 {
            get {
                return ResourceManager.GetString("MSG_MESS_0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy thi gặp vấn đề.
        /// </summary>
        public static string MSG_MESS_0038 {
            get {
                return ResourceManager.GetString("MSG_MESS_0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập | Bị gián đoạn lúc thi.
        /// </summary>
        public static string MSG_MESS_0039 {
            get {
                return ResourceManager.GetString("MSG_MESS_0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú ý: Nếu nộp bài thì bạn sẽ kết thúc thi và không thể làm thêm được nữa! Bạn có chắc chắn nộp bài?.
        /// </summary>
        public static string MSG_MESS_0040 {
            get {
                return ResourceManager.GetString("MSG_MESS_0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Khi soạn thảo trong Word phải click Save (hoặc nhấn phím Ctrl+S) liên tục để lưu văn bản đã soạn thảo.
        ///2. Sau khi soạn thảo xong, cần tắt Word, quay về cửa sổ thi;
        ///3. Khi quay về cửa sổ thi, nhấn nút “Đọc dữ liệu từ file” để nạp dữ liệu đã soạn thảo vào vùng văn bản đáp án.
        ///4. Không dùng Save As để lưu bài viết ra file khác.
        ///5. Để soạn thảo được nội dung có chứa kí hiệu, công thức toán học, thí sinh chọn Insert  Object. Trong cửa sổ Object vừa hiện lên ta chọn vào Microsoft Equation 3.0 trong phần O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MSG_MESS_0041 {
            get {
                return ResourceManager.GetString("MSG_MESS_0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hiểu rõ, bắt đầu soạn thảo.
        /// </summary>
        public static string MSG_MESS_0042 {
            get {
                return ResourceManager.GetString("MSG_MESS_0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string MSG_MESS_0043 {
            get {
                return ResourceManager.GetString("MSG_MESS_0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh cần đọc kỹ!.
        /// </summary>
        public static string MSG_MESS_0044 {
            get {
                return ResourceManager.GetString("MSG_MESS_0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh đã vi phạm quy chế thi 3 lần. Bài thi bị hủy.
        /// </summary>
        public static string MSG_MESS_0045 {
            get {
                return ResourceManager.GetString("MSG_MESS_0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh sẵn sàng làm bài (Load đề thi thành công).
        /// </summary>
        public static string MSG_MESS_0046 {
            get {
                return ResourceManager.GetString("MSG_MESS_0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập lại nhưng đã hết thời gian làm bài. Cần xem lại bài thi.
        /// </summary>
        public static string MSG_MESS_0047 {
            get {
                return ResourceManager.GetString("MSG_MESS_0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh đã ký nộp bài.
        /// </summary>
        public static string MSG_MESS_0048 {
            get {
                return ResourceManager.GetString("MSG_MESS_0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh bị cấm thi.
        /// </summary>
        public static string MSG_MESS_0049 {
            get {
                return ResourceManager.GetString("MSG_MESS_0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh đang được tạm chờ. Vui lòng chờ....
        /// </summary>
        public static string MSG_MESS_0050 {
            get {
                return ResourceManager.GetString("MSG_MESS_0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí sinh đang nhập sai phòng thi.
        /// </summary>
        public static string MSG_MESS_0051 {
            get {
                return ResourceManager.GetString("MSG_MESS_0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string MSG_MESS_0070 {
            get {
                return ResourceManager.GetString("MSG_MESS_0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PLAY_MEDIA {
            get {
                object obj = ResourceManager.GetObject("PLAY_MEDIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3001.
        /// </summary>
        public static string PORT_SUPER {
            get {
                return ResourceManager.GetString("PORT_SUPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3001.
        /// </summary>
        public static string PORT_SUPERVISOR {
            get {
                return ResourceManager.GetString("PORT_SUPERVISOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYCHUTHI.
        /// </summary>
        public static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap STOP_MEDIA {
            get {
                object obj = ResourceManager.GetObject("STOP_MEDIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
