//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    
    public partial class ANSWERSHEET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANSWERSHEET()
        {
            this.ANSWERSHEET_DETAILS = new HashSet<ANSWERSHEET_DETAILS>();
            this.ANSWERSHEET_SPEAKING = new HashSet<ANSWERSHEET_SPEAKING>();
            this.ANSWERSHEET_WRITING = new HashSet<ANSWERSHEET_WRITING>();
        }
    
        public int AnswerSheetID { get; set; }
        public Nullable<double> TestScores { get; set; }
        public Nullable<double> EssayPoints { get; set; }
        public int Status { get; set; }
        public int ContestantTestID { get; set; }
        public Nullable<int> StaffID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWERSHEET_DETAILS> ANSWERSHEET_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWERSHEET_SPEAKING> ANSWERSHEET_SPEAKING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWERSHEET_WRITING> ANSWERSHEET_WRITING { get; set; }
        public virtual CONTESTANTS_TESTS CONTESTANTS_TESTS { get; set; }
        public virtual STAFF STAFF { get; set; }

        public ANSWERSHEET (DataRow row)
        {
            this.AnswerSheetID = Convert.ToInt32(row["AnswerSheetID"]);
            this.TestScores = row["TestScores"] as Nullable<double> != null ? row["TestScores"] as Nullable<double> : default(Nullable<double>);
            this.EssayPoints = row["EssayPoints"] as Nullable<double> != null ? row["EssayPoints"] as Nullable<double> : default(Nullable<double>);
            this.Status = Convert.ToInt32(row["Status"]);
            this.ContestantTestID = Convert.ToInt32(row["ContestantTestID"]);        
            this.StaffID = row["StaffID"] as Nullable<int> != null ? row["StaffID"] as Nullable<int> : default(Nullable<int>);
        }
    }
}
