//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class ANSWER
    {
        public int AnswerID { get; set; }
        public string AnswerContent { get; set; }
        public bool IsCorrect { get; set; }
        public int SubQuestionID { get; set; }
        public Nullable<int> HeightToDisplay { get; set; }

        public virtual SUBQUESTION SUBQUESTION { get; set; }

        public ANSWER(DataRow row)
        {
            this.AnswerID = Convert.ToInt32(row["AnswerID"]);
            this.AnswerContent = row["AnswerContent"].ToString();
            this.IsCorrect = Convert.ToBoolean(row["IsCorrect"]);
            this.SubQuestionID = Convert.ToInt32(row["SubQuestionID"]);
            this.HeightToDisplay = row["HeightToDisplay"] as Nullable<int> != null ? row["HeightToDisplay"] as Nullable<int> : default(Nullable<int>);
        }

        public ANSWER () { }
    }
}
