//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWERSHEET_SPEAKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANSWERSHEET_SPEAKING()
        {
            this.SPEAKING_TEACHER = new HashSet<SPEAKING_TEACHER>();
        }
    
        public int AnswerSheetSpeakingID { get; set; }
        public Nullable<int> AnswerSheetID { get; set; }
        public Nullable<double> SpeakingScore { get; set; }
        public Nullable<double> SpeakingScore2 { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ANSWERSHEET ANSWERSHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPEAKING_TEACHER> SPEAKING_TEACHER { get; set; }
    }
}
