//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;

    public partial class ANSWERSHEET_DETAILS
    {
        public int AnswerSheetDetailID { get; set; }
        public Nullable<int> ChoosenAnswer { get; set; }
        public string AnswerContent { get; set; }
        public Nullable<int> LastTime { get; set; }
        public int Status { get; set; }
        public int AnswerSheetID { get; set; }
        public int SubQuestionID { get; set; }
        public Nullable<double> Score { get; set; }
        public string Comment { get; set; }
        public byte[] AnswerSheetFile { get; set; }
    
        public virtual ANSWERSHEET ANSWERSHEET { get; set; }
        public virtual SUBQUESTION SUBQUESTION { get; set; }

        public ANSWERSHEET_DETAILS (DataRow row)
        {
            this.AnswerSheetDetailID = Convert.ToInt32(row["AnswerSheetDetailID"]);
            this.ChoosenAnswer = row["ChoosenAnswer"] as Nullable<int> != null ? row["ChoosenAnswer"] as Nullable<int> : default(Nullable<int>);
            this.AnswerContent = row["AnswerContent"] as string != null ? row["AnswerContent"].ToString(): null;
            this.LastTime = row["LastTime"] as Nullable<int> != null ? row["LastTime"] as Nullable<int> : default(Nullable<int>);
            this.Status = Convert.ToInt32(row["Status"]);
            this.AnswerSheetID = Convert.ToInt32(row["AnswerSheetID"]);
            this.SubQuestionID = Convert.ToInt32(row["SubQuestionID"]);
            this.Score = row["Score"] as Nullable<double> != null ? row["Score"] as Nullable<double> : default(Nullable<int>);
            this.Comment = row["Comment"].ToString();
            this.AnswerSheetFile = Encoding.ASCII.GetBytes(row["AnswerSheetFile"].ToString());
        }
        public ANSWERSHEET_DETAILS() { }
    }
}
