//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTESTANTPAUSE
    {
        public int ContestantPauseID { get; set; }
        public Nullable<int> ContestantTestID { get; set; }
        public Nullable<int> ContestantPauseClickTime { get; set; }
        public Nullable<int> ContestantRealPauseTime { get; set; }
        public Nullable<int> ContestantRestartTime { get; set; }
        public string Note { get; set; }
        public Nullable<int> ContestantRealRestartTime { get; set; }
    
        public virtual CONTESTANTS_TESTS CONTESTANTS_TESTS { get; set; }
    }
}
