//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISION_SHIFTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIVISION_SHIFTS()
        {
            this.BAGOFTESTS = new HashSet<BAGOFTEST>();
            this.CONTESTANTS_SHIFTS = new HashSet<CONTESTANTS_SHIFTS>();
            this.DIVISIONSHIFT_SUPERVISOR = new HashSet<DIVISIONSHIFT_SUPERVISOR>();
            this.DIVSIONSHIFT_PAUSE = new HashSet<DIVSIONSHIFT_PAUSE>();
        }
    
        public int DivisionShiftID { get; set; }
        public int Status { get; set; }
        public int ShiftID { get; set; }
        public int RoomTestID { get; set; }
        public string Key { get; set; }
        public Nullable<int> CheckFinger { get; set; }
        public Nullable<int> StartDate { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<int> DivisionShiftAddTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAGOFTEST> BAGOFTESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTESTANTS_SHIFTS> CONTESTANTS_SHIFTS { get; set; }
        public virtual ROOMTEST ROOMTEST { get; set; }
        public virtual SHIFT SHIFT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIVISIONSHIFT_SUPERVISOR> DIVISIONSHIFT_SUPERVISOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIVSIONSHIFT_PAUSE> DIVSIONSHIFT_PAUSE { get; set; }
    }
}
