//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVSIONSHIFT_PAUSE
    {
        public int DivisionShiftPauseID { get; set; }
        public Nullable<int> DivisionShiftID { get; set; }
        public Nullable<int> DivisionShiftPauseClickTime { get; set; }
        public Nullable<int> DivisionShiftRealPauseTime { get; set; }
        public Nullable<int> DivisionShiftRestartTime { get; set; }
        public string Note { get; set; }
    
        public virtual DIVISION_SHIFTS DIVISION_SHIFTS { get; set; }
    }
}
