//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    
    public partial class PART
    {
        public int PartID { get; set; }
        public Nullable<int> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> CreateStaffID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderOfQuestion { get; set; }
        public Nullable<int> OrderInTest { get; set; }
        public Nullable<int> Shuffle { get; set; }
    
        public virtual SCHEDULE SCHEDULE { get; set; }
        public virtual STAFF STAFF { get; set; }

        public PART (DataRow row)
        {
            this.PartID = Convert.ToInt32(row["PartID"]);
            this.CreatedDate = row["CreatedDate"] as Nullable<int> != null ? row["CreatedDate"] as Nullable<int> : default(Nullable<int>);
            this.Status = row["Status"] as Nullable<int> != null ? row["Status"] as Nullable<int> : default(Nullable<int>);
            this.ScheduleID = row["ScheduleID"] as Nullable<int> != null ? row["ScheduleID"] as Nullable<int> : default(Nullable<int>);
            this.CreateStaffID = row["CreateStaffID"] as Nullable<int> != null ? row["CreateStaffID"] as Nullable<int> : default(Nullable<int>);
            this.Name = row["Name"].ToString();
            this.OrderOfQuestion = row["OrderOfQuestion"] as Nullable<int> != null ? row["OrderOfQuestion"] as Nullable<int> : default(Nullable<int>);
            this.OrderInTest = row["OrderInTest"] as Nullable<int> != null ? row["OrderInTest"] as Nullable<int> : default(Nullable<int>);
            this.Shuffle = row["Shuffle"] as Nullable<int> != null ? row["Shuffle"] as Nullable<int> : default(Nullable<int>);
        }

        public PART() { }
    }
}
