//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;
    
    public partial class QUESTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTION()
        {
            this.SUBQUESTIONS = new HashSet<SUBQUESTION>();
            this.TEST_DETAILS = new HashSet<TEST_DETAILS>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionContent { get; set; }
        public int QuestionFormat { get; set; }
        public Nullable<int> Level { get; set; }
        public bool IsQuiz { get; set; }
        public bool IsSingleChoice { get; set; }
        public bool IsParagraph { get; set; }
        public bool IsQuestionContent { get; set; }
        public int NumberSubQuestion { get; set; }
        public int NumberAnswer { get; set; }
        public Nullable<int> Type { get; set; }
        public byte[] Audio { get; set; }
        public Nullable<int> HeightToDisplay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBQUESTION> SUBQUESTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST_DETAILS> TEST_DETAILS { get; set; }

        public QUESTION (DataRow row)
        {
            this.QuestionID = Convert.ToInt32(row["QuestionID"]);
            this.QuestionContent = row["QuestionContent"].ToString();
            this.QuestionFormat = Convert.ToInt32(row["QuestionFormat"]);
            this.Level = row["Level"] as Nullable<int> != null ? Convert.ToInt32(row["Level"]) : default(Nullable<int>);
            this.IsQuiz = Convert.ToBoolean(row["IsQuiz"]);
            this.IsSingleChoice = Convert.ToBoolean(row["IsSingleChoice"]);
            this.IsParagraph = Convert.ToBoolean(row["IsParagraph"]);
            this.IsQuestionContent = Convert.ToBoolean(row["IsQuestionContent"]);
            this.NumberSubQuestion = Convert.ToInt32(row["NumberSubQuestion"]);
            this.NumberAnswer = Convert.ToInt32(row["NumberAnswer"]);
            this.Type = row["Type"] as Nullable<int> != null ? Convert.ToInt32(row["Type"]) : default(Nullable<int>);
            this.Audio = row["Audio"] as byte[] != null ? row["Audio"] as byte[] : null;
            this.HeightToDisplay = row["HeightToDisplay"] as Nullable<int> != null ? Convert.ToInt32(row["HeightToDisplay"]) : default(Nullable<int>);
        }
    }
}
