//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFTSPAUSE
    {
        public int ShiftPauseID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> ShiftPauseClickTime { get; set; }
        public Nullable<int> ShiftRealPauseTime { get; set; }
        public Nullable<int> ShiftRestartTime { get; set; }
        public string Note { get; set; }
    
        public virtual SHIFT SHIFT { get; set; }
    }
}
