//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEAKING_TEACHER
    {
        public int ID { get; set; }
        public int AnswerSheetSpeakingID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ANSWERSHEET_SPEAKING ANSWERSHEET_SPEAKING { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
