//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    
    public partial class SUBQUESTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBQUESTION()
        {
            this.ANSWERS = new HashSet<ANSWER>();
            this.ANSWERSHEET_DETAILS = new HashSet<ANSWERSHEET_DETAILS>();
        }
    
        public int SubQuestionID { get; set; }
        public string SubQuestionContent { get; set; }
        public Nullable<double> Score { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> HeightToDisplay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWER> ANSWERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWERSHEET_DETAILS> ANSWERSHEET_DETAILS { get; set; }
        public virtual QUESTION QUESTION { get; set; }

        public SUBQUESTION (DataRow row)
        {
            this.SubQuestionID = Convert.ToInt32(row["SubQuestionID"]);
            this.SubQuestionContent = row["SubQuestionContent"].ToString();
            this.Score = row["Score"] as Nullable<double> != null ? row["Score"] as Nullable<double> : default(Nullable<int>);
            this.QuestionID = Convert.ToInt32(row["QuestionID"]);
            this.HeightToDisplay = row["HeightToDisplay"] as Nullable<int> != null ? row["HeightToDisplay"] as Nullable<int> : default(Nullable<int>);
        }
    }
}
